services:
  db:
    image: postgres:16
    container_name: cyberguard_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: cyberguard
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama:latest
    container_name: cyberguard_ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    entrypoint: [ "/bin/sh", "-c", "ollama serve & sleep 5 && ollama pull nomic-embed-text && ollama pull phi3 && ollama pull llava:7b && wait" ]
  backend:
    build:
      context: ./backend
    container_name: cyberguard_backend
    restart: unless-stopped
    depends_on:
      - db
      - ollama
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/cyberguard
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      OLLAMA_BASE_URL: http://ollama:11434
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
      - ./backend/faiss_index:/app/faiss_index
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend
    container_name: cyberguard_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  pgdata:
  ollama_models:
